<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<MinVerDefaultPreReleaseIdentifiers>preview.0</MinVerDefaultPreReleaseIdentifiers>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>ChosenFewSoftware.Avalonia.Controls</PackageId>
		<Authors>Isabelle Santin</Authors>
		<Company>Chosen Few Software</Company>
		<PackageTags>user interface;graphics;imagesharp;avalonia;plugin</PackageTags>
		<Description>
			Chosen Few Software's custom controls library based on Avalonia
		</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/IsaMorphic/CFS.Avalonia.Controls</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
	
	<PropertyGroup>
		<SixLaborsLicenseKey>$(SIXLABORS_LICENSE_KEY)</SixLaborsLicenseKey>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MinVer" Version="7.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="SixLabors.ImageSharp" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
